//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DulceCafeParcial
{


    public partial class Encuesta
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.WebControls.Label lblReq1;

        protected global::System.Web.UI.WebControls.RadioButton rbQ1Muy;

        protected global::System.Web.UI.WebControls.RadioButton rbQ1Satis;

        protected global::System.Web.UI.WebControls.RadioButton rbQ1Neutral;

        protected global::System.Web.UI.WebControls.RadioButton rbQ1Insatis;

        protected global::System.Web.UI.WebControls.RadioButton rbQ1MuyInsatis;

        protected global::System.Web.UI.WebControls.RadioButton rbQ2Excel;

        protected global::System.Web.UI.WebControls.RadioButton rbQ2Bueno;

        protected global::System.Web.UI.WebControls.RadioButton rbQ2Regular;

        protected global::System.Web.UI.WebControls.RadioButton rbQ2Mala;

        protected global::System.Web.UI.WebControls.RadioButton rbQ3Si;

        protected global::System.Web.UI.WebControls.RadioButton rbQ3No;

        protected global::System.Web.UI.WebControls.Button btnSubmit;

        protected global::System.Web.UI.WebControls.Button btnBack;

        protected global::System.Web.UI.WebControls.Label lblMessage;

        protected global::System.Web.UI.WebControls.LinkButton lnkLogout;
    }
}
