//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DulceCafeParcial
{


    public partial class Factura
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.WebControls.Label lblCalcMessage;

        protected global::System.Web.UI.WebControls.ValidationSummary ValidationSummary1;

        protected global::System.Web.UI.WebControls.TextBox txtCustomerName;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator reqCustName;

        protected global::System.Web.UI.WebControls.TextBox txtCustomerPhone;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator reqCustPhone;

        protected global::System.Web.UI.WebControls.RegularExpressionValidator revCustPhone;

        protected global::System.Web.UI.WebControls.TextBox txtCustomerEmail;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator reqCustEmail;

        protected global::System.Web.UI.WebControls.RegularExpressionValidator revCustEmail;

        protected global::System.Web.UI.WebControls.TextBox txtInvoiceNumber;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator reqInvoiceNumber;

        protected global::System.Web.UI.WebControls.TextBox txtInvoiceDate;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator reqInvoiceDate;

        protected global::System.Web.UI.WebControls.DropDownList ddlProduct;

        protected global::System.Web.UI.WebControls.DropDownList ddlPresentation;

        protected global::System.Web.UI.WebControls.TextBox txtQuantity;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator reqQuantity;

        protected global::System.Web.UI.WebControls.RegularExpressionValidator revQuantity;

        protected global::System.Web.UI.WebControls.TextBox txtUnitPrice;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator reqUnitPrice;

        protected global::System.Web.UI.WebControls.RegularExpressionValidator revUnitPrice;

        protected global::System.Web.UI.WebControls.TextBox txtDiscount;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator reqDiscount;

        protected global::System.Web.UI.WebControls.RegularExpressionValidator revDiscount;

        protected global::System.Web.UI.WebControls.Button btnAddToCart;
        protected global::System.Web.UI.WebControls.DropDownList ddlCurrency;

        protected global::System.Web.UI.WebControls.GridView gvCart;

        protected global::System.Web.UI.WebControls.Button btnCalculate;

        protected global::System.Web.UI.WebControls.Button btnClear;

        protected global::System.Web.UI.WebControls.Button btnContinue;

        protected global::System.Web.UI.WebControls.Label lblProduct;

        protected global::System.Web.UI.WebControls.TextBox txtDescription;

        protected global::System.Web.UI.WebControls.Label lblSubtotal;

        protected global::System.Web.UI.WebControls.Label lblDiscountValue;

        protected global::System.Web.UI.WebControls.Label lblAfterDiscount;

        protected global::System.Web.UI.WebControls.Label lblIVA;

        protected global::System.Web.UI.WebControls.Label lblTotal;
    }
}
