//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DulceCafeParcial
{


    public partial class Registro
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.WebControls.ValidationSummary ValidationSummary1;

        protected global::System.Web.UI.WebControls.TextBox txtFullName;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator reqFullName;

        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator reqEmail;

        protected global::System.Web.UI.WebControls.RegularExpressionValidator revEmail;

        protected global::System.Web.UI.WebControls.TextBox txtPhone;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator reqPhone;

        protected global::System.Web.UI.WebControls.RegularExpressionValidator revPhone;

        protected global::System.Web.UI.WebControls.TextBox txtPassword;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator reqPassword;

        protected global::System.Web.UI.WebControls.TextBox txtConfirm;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator reqConfirm;

        protected global::System.Web.UI.WebControls.CompareValidator cmpPassword;

        protected global::System.Web.UI.WebControls.Button btnRegister;

        protected global::System.Web.UI.WebControls.HyperLink hlBack;

        protected global::System.Web.UI.WebControls.Label lblMessage;
    }
}
